version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:20.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup private key
          command: echo "$FIREBASE_PRIVATE_KEY" > private-key.txt
      - run:
          name: Install & Run Backend
          command: |
            cd backend
            npm install
            export FIREBASE_PRIVATE_KEY=$(cat ../private-key.txt)
            node index.js
    environment:
      FIREBASE_API_KEY: $FIREBASE_API_KEY
      FIREBASE_CLIENT_EMAIL: $FIREBASE_CLIENT_EMAIL
      FIREBASE_PRIVATE_KEY: $FIREBASE_PRIVATE_KEY
      FIREBASE_PRIVATE_KEY_ID: $FIREBASE_PRIVATE_KEY_ID
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      GEMINI_API_KEY: $GEMINI_API_KEY
      NEWS_API_KEY: $NEWS_API_KEY
      R2_ACCESS_KEY_ID: $R2_ACCESS_KEY_ID
      R2_SECRET_ACCESS_KEY: $R2_SECRET_ACCESS_KEY

workflows:
  version: 2
  scheduled-deploy:
    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - deploy
