version: 2.1

workflows:
  version: 2
  scheduled-deploy:
    triggers:
      - schedule:
          cron: "0 */8 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - deploy
  manual-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: /.*/

jobs:
  deploy:
    docker:
      - image: cimg/node:20.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Fix private key
          command: echo "$FIREBASE_PRIVATE_KEY" > private-key.txt
      - run:
          name: Build Project
          working_directory: backend
          command: |
            npm install
            export FIREBASE_PRIVATE_KEY=$(cat ../private-key.txt)
            node index.js
          environment:
            FIREBASE_API_KEY: ${FIREBASE_API_KEY}
            FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
            FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
            FIREBASE_PRIVATE_KEY_ID: ${FIREBASE_PRIVATE_KEY_ID}
            FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
            GEMINI_API_KEY: ${GEMINI_API_KEY}
            NEWS_API_KEY: ${NEWS_API_KEY}
            R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
            R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
