version: 2.1

parameters:
  environment:
    type: string
    default: "auto"

workflows:
  version: 2
  scheduled-deploy:
    triggers:
      - schedule:
          cron: "0 0,4,8,12,16,20 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - deploy
  manual-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: /.*/

jobs:
  deploy:
    docker:
      - image: cimg/node:20.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Fix private key
          command: echo "$FIREBASE_PRIVATE_KEY" > private-key.txt  
      -run:
          name: test
          command:  node -e 'console.log("process.env.DEPLOY_ENV =", process.env.DEPLOY_ENV)
      - run:
          name: Build Project
          working_directory: backend
          command: |
            npm install
            export FIREBASE_PRIVATE_KEY=$(cat ../private-key.txt)
            node index.js
          no_output_timeout: 420
