name: 🔥 Skibidi tuvalet 🔥

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  deploy:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Fix private key
        run: echo "${{ secrets.FIREBASE_PRIVATE_KEY }}" > private-key.txt
      - name: Build Project
        working-directory: backend
        run: |
          npm install
          export FIREBASE_PRIVATE_KEY=$(cat ../private-key.txt)
          node index.js
        env:
            FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
            FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
            FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
            FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
            FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
            R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
